name: Go

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    tags:
      - 'v*'
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go-version: [ '1.17', '1.18', '1.19' ]

    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go-version }}

    - name: Build
      run: go build -v -buildmode=plugin ./...

    - name: Test
      run: go test -race -coverprofile=coverage.out -covermode=atomic -v ./...

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3

    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v4
      if: startsWith(github.ref, 'refs/tags/')
      with:
        version: latest
        args: release --rm-dist
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
